export const ActivityAction = {
  PROJECT_CREATED:     'PROJECT_CREATED',
  PROJECT_UPDATED:     'PROJECT_UPDATED',
  PROJECT_DELETED:     'PROJECT_DELETED',
  MEMBER_INVITED:      'MEMBER_INVITED',
  MEMBER_REMOVED:      'MEMBER_REMOVED',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  TASK_CREATED:        'TASK_CREATED',
  TASK_UPDATED:        'TASK_UPDATED',
  TASK_DELETED:        'TASK_DELETED',
  TASK_ASSIGNED:       'TASK_ASSIGNED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  COMMENT_CREATED:     'COMMENT_CREATED',
  COMMENT_UPDATED:     'COMMENT_UPDATED',
  COMMENT_DELETED:     'COMMENT_DELETED',
} as const;

export type ActivityActionType = (typeof ActivityAction)[keyof typeof ActivityAction];
